---
title: "Examples of meQTLs in Non-ART vs. ART trios"
author: "Håkon K. Gjessing"
date: 2020-10-14
output: pdf_document
fig_width: 13
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
# knitr::opts_chunk$set(fig.width=12) 
```

# meQTL: No
# ART-effect: No
```{r , echo = FALSE, results = "hide"}
p.sim(levs = rep("LLLL", 6))
```

# meQTL: No
# ART-effect: No
```{r , echo = FALSE, results = "hide"}
p.sim(levs = rep("MMMM", 6))
```

# meQTL: No
# ART-effect: Yes
```{r , echo = FALSE, results = "hide"}
p.sim(levs = c(rep("MMMM", 3), rep("HHHH", 3)))
```

# meQTL: Yes
# ART-effect: No
```{r , echo = FALSE, results = "hide"}
p.sim(levs = c(rep("LHHH", 3), rep("LHHH", 3)))
```

# meQTL: Yes
# ART-effect: Yes (after fertilization?)
```{r , echo = FALSE, results = "hide"}
p.sim(levs = c(rep("LHHH", 3), c("LHHH", "LHHH", "LLLL")))
```

# meQTL: Yes
# ART-effect: Yes
# POO ART-effect: Yes (maternal line?)
```{r , echo = FALSE, results = "hide"}
p.sim(levs = c(rep("LHHH", 3), c("LHHH", "LHHH", "LHLH")))
```

# meQTL: Yes
# ART-effect: Yes
# POO ART-effect: Yes (paternal line?)
```{r , echo = FALSE, results = "hide"}
p.sim(levs = c(rep("LHHH", 3), c("LHHH", "LHHH", "LLHH")))
```




```{r , echo = FALSE, results = "hide"}
knitr::knit_exit()
```


